<?
$this->headTitle('Qu Plupload');
$this->placeholder('title')->set('Qu Plupload');
$this->headLink()
    ->prependStylesheet('js/plugins/bootstrap.min.css')
    ->prependStylesheet('js/plugins/plupload/style.css')
    ->prependStylesheet('js/plugins/plupload' . '/js/jquery.plupload.queue/css/jquery.plupload.queue.css');
$this->headScript()
    ->prependFile('js/plugins/plupload' . '/jquery/jquery-ui-1.8.23.custom.min.js', 'text/javascript')
    ->prependFile('js/plugins/plupload' . '/jquery/jquery-1.8.1.min.js', 'text/javascript');
?>
<div class="container">
    <div class="row">
        <div class="span12">
            <div class="shadow">


                <div class="test plupload_header">
                    <div class="plupload_header_content">
                        <div class="plupload_header_title">
                            ZF2 Module for Plupload, PhpThumb and included Database
                        </div>
                    </div>
                </div>


                <div class="PluploadLoad">
                    <?php echo $this->PluploadHelpLoad($id); ?>
                </div>


                <div class="clear"></div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="span12">
            <div class="shadow">


                <div id="uploader"></div>
                <?php echo $this->PluploadHelp('uploader'); ?>

          </div>
        </div>
    </div>

</div>


<!-- DISQUS -->
<div class="container">
    <div class="row">
        <div class="span12">
            <br><br>
            <div id="disqus_thread"></div>
            <script type="text/javascript">
                var disqus_shortname = 'qumodules';
                (function() {
                    var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                    dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
                })();
            </script>
        </div>
    </div>
</div>
